### ISSUE TITLE
AccountApi::getEmailVerificationToken doesn't work

### ISSUE THREAD

**Issue by andrewgorton-reachplc** [LoginRadius/java-sdk#13]
Specifically it returns "API secret is missing".

However, changing the code within the method from

        queryParameters.put("apiSecret", LoginRadiusSDK.getApiSecret());

to

        queryParameters.put("apisecret", LoginRadiusSDK.getApiSecret());

makes it work successfully (but then the capitalisation is at odds with other methods).

**Comment by indrasen715** [comment]
Hi @andrewgorton-reachplc ,

Thanks for posting your query,

We have checked the following and are unable to replicate the issue from our end and getEmailVerificationToken API is working fine.

It will be helpful if you can share the exact SDK version in which you are facing this issue?

Thanks & Regards
Indrasen

**Comment by indrasen715** [comment]
Hi @andrewgorton-reachplc 


I just wanted to follow up on this thread and hope that the above information will be helpful!

We will be closing this thread in a couple of days. Please feel free to revert if you have any further questions/concerns.

Regards
Indrasen
