### ISSUE TITLE
Thread leak when calling RestRequest.get

### ISSUE THREAD

**Issue by bignacio** [LoginRadius/java-sdk#3]
Greetings
there's an problem in Unirest that manifests itself when` RestRequest.get`. Every time is called, Unitrest refreshes the config (see https://github.com/Kong/unirest-java/blob/master/src/main/java/com/mashape/unirest/http/Unirest.java#L94) and creates new monitoring threads (and a few other things). 
See https://github.com/Kong/unirest-java/blob/master/src/main/java/com/mashape/unirest/http/options/Options.java#L77

While this is a problem in Unirest, the impact on this project is significant.

Thanks

**Comment by Agarwal-Sudhanshu** [comment]
Hi,
Thanks for bringing this to our notice, we have taken care of this issue in our latest release 4.0.0
